version: "3.9"

services:
  db:
    image: postgres:15
    container_name: reportminer-db
    environment:
      POSTGRES_DB: reportminer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fucklife@6999
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: reportminer-backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_NAME: reportminer
      DATABASE_USER: postgres
      DATABASE_PASSWORD: fucklife@6999
      DATABASE_HOST: db
      DATABASE_PORT: 5432

volumes:
  postgres_data:
