# Generated by Django 5.2 on 2025-07-05 13:14

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_path', models.TextField(blank=True, null=True)),
                ('file_type', models.CharField(max_length=10)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('processing_status', models.CharField(default='pending', max_length=20)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('metadata', models.TextField(blank=True, default='{}')),
                ('extraction_summary', models.TextField(blank=True, default='{}')),
                ('document_type', models.CharField(blank=True, max_length=50, null=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('uploaded_by', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'documents',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/')),
                ('type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word Document'), ('xlsx', 'Excel Sheet')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentKeyValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_name', models.CharField(max_length=255)),
                ('key_category', models.CharField(blank=True, max_length=100, null=True)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_numeric', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('section_title', models.CharField(blank=True, max_length=255, null=True)),
                ('extraction_method', models.CharField(blank=True, max_length=50, null=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(db_column='document_id', on_delete=django.db.models.deletion.CASCADE, related_name='key_values', to='ingestion.document')),
            ],
            options={
                'db_table': 'document_key_values',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DocumentTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table_name', models.CharField(blank=True, max_length=255, null=True)),
                ('table_index', models.IntegerField(blank=True, null=True)),
                ('sheet_name', models.CharField(blank=True, max_length=255, null=True)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('column_count', models.IntegerField(blank=True, null=True)),
                ('has_header', models.BooleanField(default=True)),
                ('table_data_json', models.TextField()),
                ('column_definitions_json', models.TextField(blank=True, null=True)),
                ('table_summary_json', models.TextField(blank=True, default='{}')),
                ('bbox_json', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(db_column='document_id', on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='ingestion.document')),
            ],
            options={
                'db_table': 'document_tables',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DocumentStructuredData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField()),
                ('column_number', models.IntegerField()),
                ('column_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cell_value', models.TextField(blank=True, null=True)),
                ('display_value', models.TextField(blank=True, null=True)),
                ('text_value', models.TextField(blank=True, null=True)),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('integer_value', models.BigIntegerField(blank=True, null=True)),
                ('date_value', models.DateField(blank=True, null=True)),
                ('datetime_value', models.DateTimeField(blank=True, null=True)),
                ('boolean_value', models.BooleanField(blank=True, null=True)),
                ('data_type', models.CharField(default='text', max_length=20)),
                ('cell_metadata_json', models.TextField(blank=True, default='{}')),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(db_column='document_id', on_delete=django.db.models.deletion.CASCADE, related_name='structured_data', to='ingestion.document')),
                ('table', models.ForeignKey(blank=True, db_column='table_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='ingestion.documenttable')),
            ],
            options={
                'db_table': 'document_structured_data',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DocumentTextSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_number', models.IntegerField()),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('section_id', models.CharField(blank=True, max_length=100, null=True)),
                ('section_title', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.TextField()),
                ('content_cleaned', models.TextField(blank=True, null=True)),
                ('content_length', models.IntegerField(blank=True, null=True)),
                ('word_count', models.IntegerField(blank=True, null=True)),
                ('segment_type', models.CharField(default='paragraph', max_length=50)),
                ('embedding_text', models.TextField(blank=True, null=True)),
                ('embedding_model', models.CharField(default='text-embedding-ada-002', max_length=50)),
                ('extracted_entities', models.TextField(blank=True, default='{}')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('bbox_json', models.TextField(blank=True, null=True)),
                ('font_info_json', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(db_column='document_id', on_delete=django.db.models.deletion.CASCADE, related_name='text_segments', to='ingestion.document')),
            ],
            options={
                'db_table': 'document_text_segments',
                'managed': True,
                'unique_together': {('document', 'sequence_number')},
            },
        ),
    ]
