# Generated by Django 5.2 on 2025-07-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0003_add_vector_field_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentkeyvalue',
            name='data_type',
            field=models.CharField(default='text', max_length=20),
        ),
    ]
