# Generated by Django 5.2 on 2025-07-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0004_documentkeyvalue_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word Document'), ('xlsx', 'Excel Sheet'), ('txt', 'Text File'), ('csv', 'CSV File')], max_length=10),
        ),
    ]
